# Generated by Django 3.0.6 on 2020-06-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.ImageField(default=0, upload_to='')),
                ('quantity', models.ImageField(default=0, upload_to='')),
                ('desc', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(upload_to='user/image')),
            ],
        ),
    ]
