# Generated by Django 3.0.6 on 2020-06-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200628_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='weight',
        ),
    ]
