# Generated by Django 3.0.6 on 2020-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200701_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='category_wt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
