# Generated by Django 3.0.6 on 2020-07-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200701_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_wt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
