# Generated by Django 3.0.6 on 2020-07-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200703_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_wt',
            field=models.IntegerField(default=20),
        ),
    ]
