# Generated by Django 3.0.6 on 2020-07-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_product_category_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_wt',
            field=models.IntegerField(default=0),
        ),
    ]
