# Generated by Django 3.0.6 on 2020-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200704_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_wt',
            field=models.CharField(max_length=20),
        ),
    ]
