# Generated by Django 3.0.6 on 2020-07-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200704_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_price',
            new_name='price',
        ),
    ]
