# Generated by Django 3.0.6 on 2020-07-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200705_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='category_wt',
        ),
    ]
